alias = {
    "ABADDON": "Abaddon",
    "ALCHEMIST": "Alchemist",
    "ALCH": "Alchemist",
    "ANCIENT APPARITION": "Ancient_Apparition",
    "ANCIENT": "Ancient_Apparition",
    "AA": "Ancient_Apparition",
    "ANTI-MAGE": "Anti-Mage",
    "AM": "Anti-Mage",
    "ARC WARDEN": "Arc_Warden",
    "AW": "Arc_Warden",
    "ARC": "Arc_Warden",
    "AXE": "Axe",
    "BANE": "Bane",
    "BATRIDER": "Batrider",
    "BR": "Batrider",
    "BAT": "Batrider",
    "BEASTMASTER": "Beastmaster",
    "BEAST": "Beastmaster",
    "BLOODSEEKER": "Bloodseeker",
    "BS": "Bloodseeker",
    "BOUNTY HUNTER": "Bounty_Hunter",
    "BOUNTY": "Bounty_Hunter",
    "BH": "Bounty_Hunter",
    "BREWMASTER": "Brewmaster",
    "BREW": "Brewmaster",
    "BRISTLEBACK": "Bristleback",
    "BB": "Bristleback",
    "BROODMOTHER": "Broodmother",
    "BROOD": "Broodmother",
    "CENTAUR WARRUNNER": "Centaur_Warrunner",
    "CENTAUR": "Centaur_Warrunner",
    "CW": "Centaur_Warrunner",
    "CHAOS KNIGHT": "Chaos_Knight",
    "CK": "Chaos_Knight",
    "CHEN": "Chen",
    "CLINKZ": "Clinkz",
    "CL": "Clinkz",
    "CLOCKWERK": "Clockwerk",
    "CLOCK": "Clockwerk",
    "CRYSTAL MAIDEN": "Crystal_Maiden",
    "CM": "Crystal_Maiden",
    "DARK SEER": "Dark_Seer",
    "SEER": "Dark_Seer",
    "DS": "Dark_Seer",
    "DARK WILLOW": "Dark_Willow",
    "WILLOW": "Dark_Willow",
    "DW": "Dark_Willow",
    "DAWNBREAKER": "Dawnbreaker",
    "DAWN": "Dawnbreaker",
    "DB": "Dawnbreaker",
    "DAZZLE": "Dazzle",
    "DEATH PROPHET": "Death_Prophet",
    "DP": "Death_Prophet",
    "DISRUPTOR": "Disruptor",
    "DOOM": "Doom",
    "DRAGON KNIGHT": "Dragon_Knight",
    "DK": "Dragon_Knight",
    "DROW RANGER": "Drow_Ranger",
    "DROW": "Drow_Ranger",
    "DR": "Drow_Ranger",
    "EARTH SPIRIT": "Earth_Spirit",
    "EARTH": "Earth_Spirit",
    "EARTHSHAKER": "Earthshaker",
    "ES": "Earthshaker",
    "ELDER TITAN": "Elder_Titan",
    "ET": "Elder_Titan",
    "EMBER SPIRIT": "Ember_Spirit",
    "EMBER": "Ember_Spirit",
    "ENCHANTRESS": "Enchantress",
    "ENIGMA": "Enigma",
    "FACELESS VOID": "Faceless_Void",
    "FACELESS": "Faceless_Void",
    "FV": "Faceless_Void",
    "GRIMSTROKE": "Grimstroke",
    "GYROCOPTER": "Gyrocopter",
    "GYRO": "Gyrocopter",
    "HOODWINK": "Hoodwink",
    "HUSKAR": "Huskar",
    "INVOKER": "Invoker",
    "JOKER": "Invoker",
    "INVO": "Invoker",
    "IO": "Io",
    "JAKIRO": "Jakiro",
    "JUGGERNAUT": "Juggernaut",
    "JUGG": "Juggernaut",
    "KEEPER OF THE LIGHT": "Keeper_of_the_Light",
    "KOTL": "Keeper_of_the_Light",
    "KUNKKA": "Kunkka",
    "LEGION COMMANDER": "Legion_Commander",
    "LEGION": "Legion_Commander",
    "LC": "Legion_Commander",
    "LESHRAC": "Leshrac",
    "LICH": "Lich",
    "LIFESTEALER": "Lifestealer",
    "LS": "Lifestealer",
    "LINA": "Lina",
    "LION": "Lion",
    "LONE DRUID": "Lone_Druid",
    "LONE": "Lone_Druid",
    "DRUID": "Lone_Druid",
    "LD": "Lone_Druid",
    "LUNA": "Luna",
    "LYCAN": "Lycan",
    "MAGNUS": "Magnus",
    "MARS": "Mars",
    "MEDUSA": "Medusa",
    "MEEPO": "Meepo",
    "MIRANA": "Mirana",
    "MONKEY KING": "Monkey_King",
    "MK": "Monkey_King",
    "WUKONG": "Monkey_King",
    "MORPHLING": "Morphling",
    "MORPH": "Morphling",
    "NAGA SIREN": "Naga_Siren",
    "NAGA": "Naga_Siren",
    "NATURE'S PROPHET": "Nature's_Prophet",
    "NP": "Nature's_Prophet",
    "NECROPHOS": "Necrophos",
    "NIGHT STALKER": "Night_Stalker",
    "NS": "Night_Stalker",
    "NYX ASSASSIN": "Nyx_Assassin",
    "NYX": "Nyx_Assassin",
    "OGRE MAGI": "Ogre_Magi",
    "OGRE": "Ogre_Magi",
    "OMNIKNIGHT": "Omniknight",
    "OMNI": "Omniknight",
    "ORACLE": "Oracle",
    "OUTWORLD DESTROYER": "Outworld_Destroyer",
    "OD": "Outworld_Destroyer",
    "PANGOLIER": "Pangolier",
    "PANGO": "Pangolier",
    "PHANTOM ASSASSIN": "Phantom_Assassin",
    "PA": "Phantom_Assassin",
    "PHANTOM LANCER": "Phantom_Lancer",
    "PL": "Phantom_Lancer",
    "PHOENIX": "Phoenix",
    "PUCK": "Puck",
    "PUDGE": "Pudge",
    "PUGNA": "Pugna",
    "QUEEN OF PAIN": "Queen_of_Pain",
    "QOP": "Queen_of_Pain",
    "RAZOR": "Razor",
    "RIKI": "Riki",
    "RUBICK": "Rubick",
    "SAND KING": "Sand_King",
    "SK": "Sand_King",
    "SHADOW DEMON": "Shadow_Demon",
    "SD": "Shadow_Demon",
    "SHADOW FIEND": "Shadow_Fiend",
    "SF": "Shadow_Fiend",
    "SHADOW SHAMAN": "Shadow_Shaman",
    "SHAMAN": "Shadow_Shaman",
    "SILENCER": "Silencer",
    "SKYWRATH MAGE": "Skywrath_Mage",
    "MAGE": "Skywrath_Mage",
    "SKYWRATH": "Skywrath_Mage",
    "SKY": "Skywrath_Mage",
    "SLARDAR": "Slardar",
    "SLARK": "Slark",
    "SNAPFIRE": "Snapfire",
    "SNIPER": "Sniper",
    "SNIP": "Sniper",
    "SPECTRE": "Spectre",
    "SPEC": "Spectre",
    "SPIRIT BREAKER": "Spirit_Breaker",
    "SB": "Spirit_Breaker",
    "BARA": "Spirit_Breaker",
    "STORM SPIRIT": "Storm_Spirit",
    "STORM": "Storm_Spirit",
    "SS": "Storm_Spirit",
    "SVEN": "Sven",
    "TECHIES": "Techies",
    "TECH": "Techies",
    "TEMPLAR ASSASSIN": "Templar_Assassin",
    "TA": "Templar_Assassin",
    "TERRORBLADE": "Terrorblade",
    "TB": "Terrorblade",
    "TIDEHUNTER": "Tidehunter",
    "TIDE": "Tidehunter",
    "TH": "Tidehunter",
    "TIMBERSAW": "Timbersaw",
    "TIMBER": "Timbersaw",
    "TINKER": "Tinker",
    "TINY": "Tiny",
    "TREANT PROTECTOR": "Treant_Protector",
    "TREANT": "Treant_Protector",
    "TROLL WARLORD": "Troll_Warlord",
    "TROLL": "Troll_Warlord",
    "TUSK": "Tusk",
    "UNDERLORD": "Underlord",
    "UNDYING": "Undying",
    "URSA": "Ursa",
    "VENGEFUL SPIRIT": "Vengeful_Spirit",
    "VENGE": "Vengeful_Spirit",
    "VENOMANCER": "Venomancer",
    "VENO": "Venomancer",
    "VIPER": "Viper",
    "VISAGE": "Visage",
    "VOID SPIRIT": "Void_Spirit",
    "VOID": "Void_Spirit",
    "WARLOCK": "Warlock",
    "WEAVER": "Weaver",
    "WINDRANGER": "Windranger",
    "WR": "Windranger",
    "WINTER WYVERN": "Winter_Wyvern",
    "WINTER": "Winter_Wyvern",
    "WW": "Winter_Wyvern",
    "WITCH DOCTOR": "Witch_Doctor",
    "WD": "Witch_Doctor",
    "WITCH": "Witch_Doctor",
    "WRAITH KING": "Wraith_King",
    "WK": "Wraith_King",
    "ZEUS": "Zeus"
}
